from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from .errors import AppError


@dataclass(frozen=True, slots=True)
class PlanStep:
    title: str
    description: str
    tool_name: str
    tool_args: dict[str, Any]


TEMPLATES: tuple[dict[str, Any], ...] = (
    {
        "id": "project_brief",
        "name": "项目简报",
        "description": "把个人项目目标整理为一份包含范围、里程碑和验收清单的 Markdown 简报。",
        "goal_example": "为我的个人 Agent 项目创建一份可执行的项目简报",
        "estimated_steps": 3,
        "expected_artifacts": ["deliverables/project_brief.md"],
    },
    {
        "id": "python_starter",
        "name": "Python 起步项目",
        "description": "创建一个可通过语法检查的最小 Python CLI，并补充 README。",
        "goal_example": "创建一个最小 Python CLI 起步项目",
        "estimated_steps": 5,
        "expected_artifacts": ["src/main.py", "README.md"],
    },
    {
        "id": "readme_builder",
        "name": "README 构建器",
        "description": "根据目标生成结构清晰、可检查的项目 README。",
        "goal_example": "为我的项目生成一份包含使用方法和路线图的 README",
        "estimated_steps": 3,
        "expected_artifacts": ["README.md"],
    },
)

TEMPLATE_BY_ID = {item["id"]: item for item in TEMPLATES}


class RuleBasedAgent:
    """Deterministic offline planner shared by v1 and the compatibility API."""

    name = "rule_based"
    model = "rule-based-v1.0"

    def list_templates(self) -> list[dict[str, Any]]:
        return [dict(item) for item in TEMPLATES]

    def resolve_template(
        self, goal: str | None, template_id: str | None
    ) -> dict[str, Any]:
        if template_id:
            template = TEMPLATE_BY_ID.get(template_id)
            if template is None:
                raise AppError(
                    "TEMPLATE_NOT_FOUND",
                    f"Template '{template_id}' was not found",
                    status_code=404,
                    details={
                        "template_id": template_id,
                        "available_templates": sorted(TEMPLATE_BY_ID),
                    },
                )
            return template
        lowered = (goal or "").lower()
        if any(keyword in lowered for keyword in ("python", "cli", "脚本", "代码")):
            return TEMPLATE_BY_ID["python_starter"]
        if any(keyword in lowered for keyword in ("readme", "说明文档", "使用说明")):
            return TEMPLATE_BY_ID["readme_builder"]
        return TEMPLATE_BY_ID["project_brief"]

    def plan(
        self, *, goal: str | None, template_id: str | None
    ) -> tuple[str, str, list[PlanStep]]:
        template = self.resolve_template(goal, template_id)
        resolved_goal = _single_line(goal or template["goal_example"])
        resolved_template_id = str(template["id"])
        if resolved_template_id == "project_brief":
            steps = self._project_brief_steps(resolved_goal)
        elif resolved_template_id == "python_starter":
            steps = self._python_starter_steps(resolved_goal)
        else:
            steps = self._readme_steps(resolved_goal)
        if not 3 <= len(steps) <= 5:
            raise AppError(
                "INVALID_PLAN",
                "The generated plan must contain between 3 and 5 steps",
                status_code=500,
                details={"step_count": len(steps)},
            )
        return resolved_goal, resolved_template_id, steps

    @staticmethod
    def _project_brief_steps(goal: str) -> list[PlanStep]:
        content = f"""# Project Brief

## 目标

{goal}

## 问题与用户价值

- 明确该项目要解决的具体问题。
- 为个人用户提供可观察、可验证的结果。

## v1.0 范围

- 跑通一个最小端到端流程。
- 保存结构化执行步骤与结果。
- 对主要产物执行确定性检查。

## 里程碑

1. 建立项目骨架与数据模型。
2. 实现核心执行流程。
3. 完成检查、文档与演示。

## 验收清单

- [ ] 核心流程可以离线运行。
- [ ] 产物位于 Quest Sandbox 内。
- [ ] 执行失败可以从 Trace 定位。
"""
        return [
            PlanStep(
                "检查工作区",
                "列出 Quest 工作区的当前内容。",
                "list_directory",
                {"path": "."},
            ),
            PlanStep(
                "生成项目简报",
                "写入包含目标、范围、里程碑和验收清单的简报。",
                "write_file",
                {"path": "deliverables/project_brief.md", "content": content},
            ),
            PlanStep(
                "检查 Markdown",
                "确认项目简报非空且 Markdown 围栏完整。",
                "check_markdown",
                {"path": "deliverables/project_brief.md"},
            ),
        ]

    @staticmethod
    def _python_starter_steps(goal: str) -> list[PlanStep]:
        goal_literal = json.dumps(goal, ensure_ascii=False)
        source = f'''"""Minimal CLI generated by ProjectTown."""

import argparse


PROJECT_GOAL = {goal_literal}


def build_message(name: str) -> str:
    return f"Hello, {{name}}! Project goal: {{PROJECT_GOAL}}"


def main() -> None:
    parser = argparse.ArgumentParser(description="ProjectTown starter CLI")
    parser.add_argument("--name", default="developer")
    args = parser.parse_args()
    print(build_message(args.name))


if __name__ == "__main__":
    main()
'''
        readme = f"""# Python Starter

## 项目目标

{goal}

## 运行

```powershell
python src/main.py --name ProjectTown
```

## 文件

- `src/main.py`：最小命令行入口。
- `README.md`：运行方式与项目说明。

## v1.0 验收

- Python 文件通过 AST 语法检查。
- README 通过基础 Markdown 检查。
"""
        return [
            PlanStep("检查工作区", "列出工作区内容。", "list_directory", {"path": "."}),
            PlanStep(
                "创建 Python 入口",
                "写入最小 CLI。",
                "write_file",
                {"path": "src/main.py", "content": source},
            ),
            PlanStep(
                "检查 Python 语法",
                "使用 AST 解析源文件，不执行代码。",
                "check_python_syntax",
                {"path": "src/main.py"},
            ),
            PlanStep(
                "创建 README",
                "写入项目目标与运行说明。",
                "write_file",
                {"path": "README.md", "content": readme},
            ),
            PlanStep(
                "检查 README",
                "确认 README 的 Markdown 结构有效。",
                "check_markdown",
                {"path": "README.md"},
            ),
        ]

    @staticmethod
    def _readme_steps(goal: str) -> list[PlanStep]:
        content = f"""# Personal Project

## 项目目标

{goal}

## 快速开始

1. 阅读项目目标和范围。
2. 配置本地开发环境。
3. 运行最小示例并检查输出。

## 当前能力

- 结构化记录任务步骤。
- 在隔离工作区内生成项目产物。
- 使用确定性工具检查生成结果。

## 路线图

- [x] v1.0 Goal Contract 与 DAG
- [x] v1.0 Evidence 与独立 Verifier
- [x] v1.0 Checkpoint、幂等与恢复
"""
        return [
            PlanStep("检查工作区", "列出工作区内容。", "list_directory", {"path": "."}),
            PlanStep(
                "生成 README",
                "写入目标、快速开始、当前能力和路线图。",
                "write_file",
                {"path": "README.md", "content": content},
            ),
            PlanStep(
                "检查 README",
                "确认 README 非空且 Markdown 围栏完整。",
                "check_markdown",
                {"path": "README.md"},
            ),
        ]


def _single_line(value: str) -> str:
    return " ".join(value.replace("```", "` ` `").replace("~~~", "~ ~ ~").split())
